Documents/My Dropbox/Bitmaker Labs/photogur/config/routes.rb
Photogur::Application.routes.draw do

  root :to => "pictures#index"

  resources :pictures

 

end

Documents/My Dropbox/Bitmaker Labs/photogur/app/models/picture.rb
class Picture < ActiveRecord::Base
	attr_accessible :title, :artist, :url, :copyrighted

	validates :title, :presence => true
	validates :artist, :presence => true
	validates :url, {
		:format => {
			:with => /^https?:/, :message => "Please enter a valid URL"
		}
	}

	scope :alphabetical, order("title ASC")
end

Documents/My Dropbox/Bitmaker Labs/photogur/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Documents/My Dropbox/Bitmaker Labs/photogur/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	
	def index
		if params[:copyrighted] == "true" # /pictures?copyrighted=true
			@pictures = Picture.where(:copyrighted => true).alphabetical.all
		else
			@pictures = Picture.alphabetical.all
		end
	end

	def show
		@picture = Picture.find(params[:id])
	end

	def new
		@picture = Picture.new
	end

	def create  		
		@picture = Picture.new(params[:picture])  
		if @picture.save # returns true or false 
			redirect_to pictures_path
		else
			flash.now[:error] = "Could not save the picture. Pls try again."
			render :new  # render goes to controller and renders VIEW for #new action (without running the code in PicturesController#new!!) => keep existing data in form
		end
	end

	def edit
		@picture = Picture.find(params[:id])   
	end

	def update  # no saving necessary as update_attributes does this already
		@picture = Picture.find(params[:id])  # see comments below
		if @picture.update_attributes(params[:picture])  # see comments below
			redirect_to @picture  # alternatively: 'redirect_to picture_path(@picture)'
		else
			# do something else
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_path
	end

end


# This is what the params looks like after submitting the form

# params = {
# 	:id => "2"
# 	:picture => {
# 		:title => "some title"
# 		:artist => "some artist"
# 		:url => "some url"
# 	}
# }

Documents/My Dropbox/Bitmaker Labs/photogur/app/helpers/application_helper.rb
module ApplicationHelper
end

Documents/My Dropbox/Bitmaker Labs/photogur/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="nav">
	<ul>
		<li><%= link_to "Pictures", pictures_path %></li>
		<li><%= link_to "New Picture", new_picture_path %></li>
	</ul>
</div>

<%= yield %>

</body>
</html>

Documents/My Dropbox/Bitmaker Labs/photogur/app/views/pictures/_form.html.erb
<%= form_for @picture do |f| %>  
	<p>
		<label>Artist</label><br>
		<% if @picture.errors.messages[:artist] %>
			<p><%= @picture.errors.messages[:artist][0] %></p>
		<% end %>
		<!-- alternatively: @picture.errors[:artist].first -->
		<%= f.text_field "artist" %>
	</p>	
	<p>
		<label>Title</label><br>
		<!-- we can access value directly (without the "messages") -->
		<%= @picture.errors[:title].first %> 
		<%= f.text_field "title" %>
	</p>
	<p>
		<label>URL</label><br>
		<%= @picture.errors[:url].first %>
		<%= f.text_field "url" %>
	</p>
	<p>
		<%= f.check_box "copyrighted" %>
		<%= f.label "copyrighted", "Photo is copyrighted" %> 
		<!-- this is a Rails helper for label -->
	</p>
	<p>
		<!-- button_text is a variable defined in the edit and new views -->
		<%= f.submit button_text %> 
	</p>
<% end %>

Documents/My Dropbox/Bitmaker Labs/photogur/app/views/pictures/edit.html.erb
<h1>Edit a picture</h1>

<%= render :partial => "form", :locals => {:button_text => "Update"} %>

Documents/My Dropbox/Bitmaker Labs/photogur/app/views/pictures/index.html.erb
<h1>Index of all pictures</h1>

<%= link_to "Copyrighted pictures only", pictures_path(:copyrighted => true) %>

<% @pictures.each do |picture| %>
	<h2><%= picture.title %></h2>
	<h3><%= picture.artist %></h3>
	
	<!-- this is the way to deal with links on images... -->
	<%= link_to picture do %>  
		<%= image_tag picture.url %>  
	<% end %>

	<%= button_to "Show Details", picture, :method => :get %></p><!-- alt: link_to "...", picture_path(picture) -->

<% end %>

Documents/My Dropbox/Bitmaker Labs/photogur/app/views/pictures/new.html.erb
<h1>Add a picture</h1>

<div class="errors">
	<%= flash[:error] %>
</div>

<%= render :partial => "form", :locals => {:button_text => "Save"} %>

Documents/My Dropbox/Bitmaker Labs/photogur/app/views/pictures/show.html.erb
<h2><%= @picture.title %></h2>
<h3><%= @picture.artist %></h3>
<img src="<%= @picture.url %>">

<% if @picture.copyrighted %> <!-- i.e. if 'true' -->
	<p>This picture is copyrighted.</p>
<% end %>

<%= link_to "Edit Picture", edit_picture_path(@picture) %>
<%= link_to "Delete", @picture, :method => :delete, :confirm => "Are you sure you want to delete this picture" %>